on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: whatsapp-notify
        id: whatsapp-notify
        env:
          account_sid: AC4112994764eba818ba6857e263eeb135
          auth_token: e6e1ff627822c78b574986e6b5f4a423
          to_whatsapp_no: +6282261289515
          message: Add message wa

        uses: khaled-ibtikar/whatsapp-push-notify-action@master
